---
debian_nfs_server/nfs-kernel-server_1%3a1.2.0-4ubuntu4.1_amd64.deb:
  object_id: ba69b993-ec3f-47cf-9fb1-0fcb37212959
  sha: a44b3f8319984bace61f21bb6d15cee1419e5bf3
  size: 169618
nginx/nginx-upload-module-2.2.tar.gz:
  object_id: 161d5d5f-ffde-4e37-9b9f-151139fdc027
  sha: 74ccd116525a155db76f92a1cd484d9516a70398
  size: 28505
libmariadb/libmariadb-5.5.36.tar.xz:
  object_id: 4827612c-e535-408b-bf60-ba5f25690fdd
  sha: 4985fd30ffd60de12770153346b4485cd5dcb7ad
  size: 1260684
nginx/newrelic_nginx_agent-1.2.1.tar.gz:
  object_id: c63358f6-574a-4e20-9d2b-7e1450368b6d
  sha: 98a1b10475371705932fea4769f8ac1b0451106f
  size: 5222
nginx/nginx-1.11.1.tar.gz:
  object_id: 53e21bda-b6b2-4d6a-9d6e-1fbfa1f63ecd
  sha: 6b6172b26628b95c4ad0d6cb5b11eb4aa59c2a83
  size: 913417
nginx/headers-more-nginx-module-0.30.tar.gz:
  object_id: c9069331-8ff2-4b2f-b663-45d7230c5a39
  sha: a188a399f3e365a0831585a9d7aa0e6ed1a75f0d
  size: 27793
nginx/pcre-8.39.tar.gz:
  object_id: 0bea0468-82a8-4349-8444-2e8674a8bdfb
  sha: b3aec1f643d9701841e2f9d57ac121a7ff448fc8
  size: 2062258
postgres/postgresql-9.4.9.tar.gz:
  object_id: 412b77c8-966c-463e-84e1-e5fc47e47269
  sha: c9d641eb69885672e5aacee413cd778d88b8420d
  size: 23300245
golang/go1.7.3.linux-amd64.tar.gz:
  object_id: 2af021d2-ad99-4078-91e5-e2a7af4ab8c6
  sha: ead40e884ad4d6512bcf7b3c7420dd7fa4a96140
  size: 82565628
ruby-2.3/bundler-1.13.6.gem:
  object_id: f789d120-4a5a-4df8-b20c-6f441f292863
  sha: c4b33f5e0a6ad4a363d2820260f10454197cceff
  size: 307200
ruby-2.3/ruby-2.3.3.tar.gz:
  object_id: 12288fa4-f74a-4f5e-9067-f60536d4916d
  sha: 1014ee699071aa2ddd501907d18cbe15399c997d
  size: 17813577
ruby-2.3/rubygems-2.6.8.tgz:
  object_id: 5fd4a544-aaac-437b-8435-8931964852a5
  sha: d253fd1caca6103a9e2a69127ac158a3745fbb44
  size: 754300
